const number=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[$,]/g,''));return Number.isFinite(n)?n:null};
export function purchaseLowerBound(text){const m=String(text||'').match(/([\d,.]+)\s*([KM]?)\+?\s+bought/i);return m?Math.round(Number(m[1].replace(/,/g,''))*({K:1000,M:1000000}[m[2].toUpperCase()]||1)):null}
export function volumeOz(text){const m=String(text||'').match(/\b(\d+(?:\.\d+)?)\s*(?:fluid\s*)?(?:fl\.?\s*)?(?:oz|ounces?)\b/i);return m?Number(m[1]):null}
export function tokens(text){return String(text||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(Boolean)}
export function normalizeProduct(raw,{marketplace='US',fetchedAt=new Date().toISOString(),sourceUrl,searchRow,provider='apiguru'}={}){
 const attributes=Object.fromEntries((raw.product_attributes||raw.product_overview||[]).filter(a=>a.value!=null).map(a=>[String(a.id||a.key||a.label).toLowerCase().replace(/ /g,'_'),String(a.value)]));
 const title=raw.product_title||raw.title||'',issues=[];
 let capacity=volumeOz(attributes.capacity);if(attributes.capacity&&capacity===null)issues.push({field:'capacity',code:'INVALID_VOLUME_UNIT',raw:attributes.capacity});capacity??=volumeOz(attributes.size)||volumeOz(attributes.style)||volumeOz(title);
 const amount=number(raw.product_price??raw.price),searchPrice=number(searchRow?.product_price);if(amount!==null&&searchPrice!==null&&Math.abs(amount-searchPrice)>.01)issues.push({field:'price',code:'CONFLICTING_SNAPSHOTS',detailPrice:amount,searchPrice});
 const source={provider,url:sourceUrl||raw.details_url||raw.product_url||'https://www.amazon.com/dp/'+raw.asin,amazonUrl:raw.product_url||(Array.isArray(raw.url)?raw.url[0]:raw.url)||'https://www.amazon.com/dp/'+raw.asin,fetchedAt:raw.fetched_at||fetchedAt,marketplace};
 const purchaseRaw=raw.sales_volume||searchRow?.sales_volume||null;
 return {asin:raw.asin,parentAsin:raw.parent_asin||null,familyAsins:[...new Set([...(raw.product_variations?.all||[]),...(Array.isArray(raw.all_product_variations)?raw.all_product_variations:[])].map(x=>x.asin).filter(x=>/^[A-Z0-9]{10}$/.test(x||'')))],title,brand:raw.brand_name||raw.product_brand||attributes.brand||null,price:{amount,currency:provider==='user_browser'?(raw.currency||null):raw.currency&&raw.currency!=='$'?raw.currency:marketplace==='US'?'USD':null,searchAmount:searchPrice,primeAmount:number(raw.prime_price),source},images:raw.product_photos||raw.product_images||[],aPlus:raw.a_plus||{present:false,text:''},rating:number(raw.product_star_rating??raw.product_reviews?.rating),reviewCount:number(raw.product_num_ratings??raw.product_reviews?.count),reviewScope:'可能跨变体合并；不可当作该子 ASIN 独立销量',capacityOz:capacity,packCount:number(attributes.number_of_items)||1,material:attributes.material||null,attributes,categoryPath:raw.category_path||[],ranks:raw.ranks||[],features:Array.isArray(raw.about_product)?raw.about_product:Array.isArray(raw.product_info)?raw.product_info:[],description:raw.product_description||raw.description||'',customerSummary:raw.customers_say||null,reviewSamples:Array.isArray(raw.product_reviews)?raw.product_reviews.map(r=>({rating:r.rating||r.review_star_rating||null,text:r.text||r.review_comment||r.body||''})).slice(0,10):[],recentPurchases:{raw:purchaseRaw,lowerBound:purchaseLowerBound(purchaseRaw),kind:'Amazon displayed lower-bound badge, not exact sales',source:searchRow?{...source,url:searchRow.details_url||source.url}:source},isSponsored:Boolean(raw.is_sponsored||searchRow?.is_sponsored),isBestSeller:Boolean(raw.is_best_seller||searchRow?.is_best_seller),source,qualityIssues:issues};
}
export function inferQuery(seed){const leaf=seed.categoryPath.at(-1)?.name;let type=leaf?leaf.replace(/^Insulated\s+/i,'').replace(/s$/i,''):'';if(!type||/kitchen|home|other|organization/i.test(type))type=seed.title.toLowerCase().replace(String(seed.brand||'\u0000').toLowerCase(),'').split(/[|,]/)[0];const text=(seed.title+' '+seed.features.join(' ')).toLowerCase();const traits=['insulated','handle','straw','stainless steel','wireless','rechargeable','waterproof'].filter(x=>text.includes(x));return [seed.capacityOz?`${seed.capacityOz} oz`:'',type,...traits].filter(Boolean).join(' ').slice(0,160)}
const accessories=/replacement|lid(s)? for|straw topper|sleeve for|cover for|accessories|replacement lid/i;
export function selectCandidates(seed,rows,{limit=5}={}){
 const excluded=[],candidates=[];const seedWords=new Set(tokens(seed.title).filter(x=>x.length>3&&!tokens(seed.brand).includes(x)&&!tokens(seed.attributes.color).includes(x)));
 for(const row of rows){const p=normalizeProduct(row);let reason=null;if(p.asin===seed.asin)reason='SELF';else if(p.isSponsored)reason='SPONSORED';else if(accessories.test(p.title))reason='ACCESSORY';else if(seed.familyAsins.includes(p.asin)||p.parentAsin&&seed.parentAsin&&p.parentAsin===seed.parentAsin)reason='SAME_PARENT';else if(seed.brand&&p.title.toLowerCase().includes(seed.brand.toLowerCase()))reason='OWN_BRAND';else if(seed.capacityOz&&p.capacityOz&&Math.abs(p.capacityOz-seed.capacityOz)/seed.capacityOz>.12)reason='CAPACITY_MISMATCH';else if(/\b(?:[2-9]|\d{2,})\s*(?:pack|pcs|pieces)\b/i.test(p.title))reason='MULTIPACK';if(reason){excluded.push({asin:p.asin,reason});continue}const overlap=[...new Set(tokens(p.title))].filter(x=>seedWords.has(x)).length,sold=p.recentPurchases.lowerBound||0;const score=overlap+Math.log10(1+sold)*3+(p.isBestSeller?5:0)+(sold>0?Math.log10(1+(p.reviewCount||0))*.2:0);candidates.push({row,normalized:p,score,hasSalesSignal:sold>0||p.isBestSeller})}
 candidates.sort((a,b)=>b.score-a.score);const families=new Set(),selected=[];for(const c of candidates){const head=c.normalized.title.toLowerCase().split(/\b\d+\s*(?:oz|ounces|ml)/)[0].split(/tumbler|bottle|mug|cup|water|insulated/)[0].trim();const family=c.normalized.parentAsin||(head.length>2?head:c.normalized.title.toLowerCase().split(/[|,]/)[0]);if(families.has(family)){excluded.push({asin:c.normalized.asin,reason:'SAME_FAMILY_CANDIDATE'});continue}families.add(family);selected.push(c);if(selected.length===limit)break}return {selected,excluded};
}
export function filterDetailedCompetitors(seed,details,searchRows,{provider='apiguru'}={}){
 const selection=[],excluded=[],parents=new Set(),byAsin=new Map(searchRows.map(r=>[r.asin,r]));
 for(const raw of details){const p=normalizeProduct(raw,{searchRow:byAsin.get(raw.asin),provider});if(!p.title.trim()){excluded.push({asin:p.asin,reason:'MISSING_PRODUCT_TITLE'});continue}if(p.asin===seed.asin||seed.familyAsins.includes(p.asin)||p.parentAsin&&p.parentAsin===seed.parentAsin){excluded.push({asin:p.asin,reason:'SELF_OR_PARENT'});continue}if(seed.capacityOz&&p.capacityOz&&Math.abs(p.capacityOz-seed.capacityOz)/seed.capacityOz>.12){excluded.push({asin:p.asin,reason:'CAPACITY_MISMATCH'});continue}if(p.parentAsin&&parents.has(p.parentAsin)||selection.some(x=>x.familyAsins.includes(p.asin)||p.familyAsins.includes(x.asin))){excluded.push({asin:p.asin,reason:'SAME_COMPETITOR_PARENT'});continue}if(p.parentAsin)parents.add(p.parentAsin);const reference=seed.ranks.filter(x=>x.node_id).at(-1)||seed.ranks.at(-1);const matchingRank=p.ranks.find(r=>reference&&(reference.node_id&&r.node_id?reference.node_id===r.node_id:reference.category===r.category));p.salesEvidence={label:matchingRank?'同类目 BSR 信号':p.recentPurchases.lowerBound?'近期购买提示信号':'没有可核实的热销信号',comparableBsr:matchingRank||null,canClaimBestSelling:Boolean(matchingRank&&matchingRank.rank<=100||p.isBestSeller),caution:'购买提示是下限；搜索顺序不是销量排名；评论数可能聚合变体'};selection.push(p)}return {competitors:selection,excluded};
}
export function keywordEvidence(products){const stop=new Set('a an the and or of for to in on at by from your you our with is are it its as that this keeps keep made most all can up hours day'.split(' '));const brands=new Set(products.flatMap(p=>tokens(p.brand))),map=new Map();for(const p of products)for(const [field,text] of [['title',p.title],...p.features.map((f,i)=>['bullet_'+i,f])]){const words=tokens(text);for(const n of [2,3])for(let i=0;i<=words.length-n;i++){const group=words.slice(i,i+n);if(stop.has(group[0])||stop.has(group.at(-1))||group.some(w=>brands.has(w))||group.every(w=>/^\d+$/.test(w)))continue;const phrase=group.join(' '),list=map.get(phrase)||[];if(!list.some(x=>x.asin===p.asin&&x.field===field))list.push({asin:p.asin,field,source:p.source.amazonUrl});map.set(phrase,list)}}return [...map].map(([keyword,evidence])=>({keyword,sourceKind:'listing phrase coverage, not search-volume data',evidence,competitorCoverage:new Set(evidence.map(x=>x.asin)).size})).filter(k=>k.competitorCoverage>=2).sort((a,b)=>b.competitorCoverage-a.competitorCoverage||b.evidence.length-a.evidence.length).slice(0,30)}
