export function extractAmazonPage(kind){
 const clean=s=>String(s||'').replace(/\s+/g,' ').trim(),text=e=>clean(e?.textContent),one=s=>document.querySelector(s);
 const priceOf=e=>{const raw=text(e);const n=Number(raw.replace(/[^0-9.]/g,''));return {amount:raw&&Number.isFinite(n)?n:null,currency:/^\$/.test(raw)?'USD':/£/.test(raw)?'GBP':/€/.test(raw)?'EUR':null,raw}};
 const blocked=one('form[action*="validateCaptcha"], #captchacharacters')||/robot check|automated access/i.test(document.title);if(blocked)return {error:'AMAZON_ACCESS_CHALLENGE',message:'Amazon 返回访问验证页，未读取商品'};
 if(location.pathname.startsWith('/ap/signin'))return {error:'AMAZON_LOGIN_REQUIRED',message:'Amazon 要求登录，未读取商品'};
 if(kind==='search'){
  const cards=[...document.querySelectorAll('[data-component-type="s-search-result"][data-asin]')];const products=cards.map((card,index)=>{const asin=card.getAttribute('data-asin'),title=text(card.querySelector('h2')),p=priceOf(card.querySelector('.a-price:not(.a-text-price) .a-offscreen'));const whole=text(card);const sales=whole.match(/([\d,.]+\s*[KM]?\+?\s+bought in past month)/i)?.[1]||null;const ratings=whole.match(/([\d,.]+)\s*(?:ratings|reviews)/i)?.[1]||text(card.querySelector('a[href*="customerReviews"] span'));return {asin,product_title:title,product_price:p.amount,currency:p.currency,product_num_ratings:Number(String(ratings||'').replace(/,/g,''))||null,product_star_rating:whole.match(/(\d\.\d) out of 5 stars/i)?.[1]||null,sales_volume:sales,is_sponsored:Boolean(card.querySelector('[data-component-type*="sp-sponsored"],.puis-sponsored-label-text')||[...card.querySelectorAll('span,a')].some(e=>/^Sponsored$/i.test(text(e)))),is_best_seller:/Best Seller/.test(whole),product_url:'https://www.amazon.com/dp/'+asin,observedSearchPosition:index+1}}).filter(p=>/^[A-Z0-9]{10}$/.test(p.asin||'')&&p.product_title);
  const sort=one('#s-result-sort-select')?.value;return {products,filters_applied:{sort_by:sort==='exact-aware-popularity-rank'?'BEST_SELLERS':'RELEVANCE'},source_url:location.href};
 }
 const title=text(one('#productTitle'));if(!title)return {error:'PRODUCT_TITLE_MISSING',message:'未找到商品标题，可能页面未加载、商品不存在或访问受限'};
 const asin=one('#ASIN')?.value?.toUpperCase()||location.pathname.match(/\/dp\/([A-Z0-9]{10})/i)?.[1]?.toUpperCase();
 const attributes=[];for(const row of document.querySelectorAll('#productOverview_feature_div tr,#productDetails_techSpec_section_1 tr,#productDetails_detailBullets_sections1 tr,#productDetails_db_sections tr')){const cells=row.querySelectorAll('th,td');if(cells.length>=2&&text(cells[0])&&text(cells[1]))attributes.push({key:text(cells[0]),value:text(cells[1])})}
 const brand=text(one('#bylineInfo')).replace(/^Visit the /i,'').replace(/ Store$/i,'').replace(/^Brand:\s*/i,'')||attributes.find(x=>/^(brand|brand name)$/i.test(x.key))?.value||null;
 const p=priceOf(one('#corePriceDisplay_desktop_feature_div .a-price:not(.a-text-price) .a-offscreen,#corePrice_feature_div .a-price:not(.a-text-price) .a-offscreen,.a-price:not(.a-text-price) .a-offscreen'));
 const features=[...document.querySelectorAll('#feature-bullets .a-list-item')].map(text).filter(s=>s.length>10&&!/Make sure this fits/i.test(s));
 const ranks=[];for(const a of document.querySelectorAll('#detailBulletsWrapper_feature_div a[href*="/gp/bestsellers/"],#productDetails_detailBullets_sections1 a[href*="/gp/bestsellers/"],#productDetails_db_sections a[href*="/gp/bestsellers/"]')){const parent=a.closest('li,tr')||a.parentElement;const links=[...parent.querySelectorAll('a[href*="/gp/bestsellers/"]')];const numbers=[...text(parent).matchAll(/#([\d,]+)/g)];const m=numbers[links.indexOf(a)]||numbers[0];if(m)ranks.push({category:text(a),rank:Number(m[1].replace(/,/g,'')),node_id:a.href.match(/\/gp\/bestsellers\/[^/]+\/(\d+)/)?.[1]||null})}
 const category_path=[...document.querySelectorAll('#wayfinding-breadcrumbs_feature_div a')].map(a=>({name:text(a),link:a.href})).filter(a=>a.name);
 const parentCandidate=one('#parentASIN,#parentAsin,input[name=parentASIN],input[name=parentAsin]')?.value;const parent_asin=/^[A-Z0-9]{10}$/.test(parentCandidate||'')?parentCandidate:null;
 const variationLinks=[...document.querySelectorAll('[id^="variation_"] a[href*="/dp/"]')].map(a=>({asin:a.href.match(/\/dp\/([A-Z0-9]{10})/i)?.[1]})).filter(x=>x.asin);
 const social=text(one('#social-proofing-faceout-title-tk_bought,#social-proofing-faceout-title-tk_bought .a-text-bold'));const rating=text(one('#acrPopover .a-icon-alt,[data-hook="rating-out-of-text"]')).match(/(\d(?:\.\d)?)/)?.[1]||null;
 const count=text(one('#acrCustomerReviewText')).match(/([\d,]+)/)?.[1]||null;
 const summary=text(one('[data-hook="cr-insights-summary"],[data-csa-c-slot-id="cr-insights-summary"]'))||null;
 const reviews=[...document.querySelectorAll('#cm-cr-dp-review-list [data-hook="review"]')].slice(0,10).map(r=>({rating:text(r.querySelector('[data-hook="review-star-rating"]')).match(/\d(?:\.\d)?/)?.[0]||null,text:text(r.querySelector('[data-hook="review-body"]'))})).filter(r=>r.text);
 const images=[...document.querySelectorAll('#landingImage,#altImages img')].map(img=>img.getAttribute('data-old-hires')||img.currentSrc||img.getAttribute('src')).filter(url=>/^https:\/\/m\.media-amazon\.com\//.test(url||'')).slice(0,6);const aplus=one('#aplus_feature_div,.aplus-v2');
 return {product_photos:images,a_plus:{present:Boolean(aplus),text:text(aplus).slice(0,1500)},asin,product_title:title,brand_name:brand,product_price:p.amount,currency:p.currency,price_raw:p.raw,product_star_rating:rating,product_num_ratings:count?Number(count.replace(/,/g,'')):null,about_product:features,product_description:text(one('#productDescription')),product_overview:attributes,category_path,ranks,parent_asin,all_product_variations:variationLinks,sales_volume:social||null,is_best_seller:Boolean(one('#zeitgeistBadge_feature_div'))||features.some(s=>/Best Seller/.test(s)),customers_say:summary?{text:summary,kind:'Amazon review summary'}:null,product_reviews:reviews,product_url:'https://www.amazon.com/dp/'+asin,fetched_at:new Date().toISOString()};
}
