import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';import {webcrypto} from 'node:crypto';
const require=createRequire(import.meta.url),{parseHTML}=require('linkedom');const makeStorage=(seed={})=>({data:new Map(Object.entries(seed)),getItem(k){return this.data.get(k)??null},setItem(k,v){this.data.set(k,String(v))}});
function appRuntime(){const html=readFileSync('docs/index.html','utf8'),{document,HTMLElement}=parseHTML(html);HTMLElement.prototype.focus=()=>{};const source=html.match(/<script>([\s\S]*)<\/script>/)[1];const events=[],sent=[],http=[];const win={addEventListener(type,fn){if(type==='message')events.push(fn)},postMessage(message){sent.push(message);setTimeout(()=>{for(const listener of events)listener({source:win,origin:'https://yuwannn122.github.io',data:{channel:'AMAZON_OPS_DATA_V1',direction:'to_page',id:message.id,ok:true,result:message.action==='ping'?{installed:true}:bundle()}})},0)}};const secret='sk-private-fixture-secret';const context=vm.createContext({window:win,document,location:new URL('https://yuwannn122.github.io/amazon-ops-assistant/'),localStorage:makeStorage({listing_lab_profile:'Tester'}),sessionStorage:makeStorage({amazon_ds_key:secret}),crypto:webcrypto,setTimeout,clearTimeout,AbortSignal,Blob,URL,console,alert:()=>{},fetch:async(url,options)=>{http.push({url,options});return Response.json({choices:[{message:{content:JSON.stringify({summary:'真实资料分析',title:'Brand 30 oz Tumbler',item_highlights:'Stainless steel tumbler with handle and straw',bullets:['Feature one','Feature two','Feature three','Feature four','Feature five'],description:'Evidence based description',search_terms:[],keyword_opportunities:[],changes:[],risks:[]})}}]})}});vm.runInContext(source,context);return {context,document,sent,http,secret}}
function bundle(){const source={provider:'user_browser',amazonUrl:'https://www.amazon.com/dp/B000000001',fetchedAt:'2026-10-07T00:00:00Z'};return {status:'evidence_ready',asin:'B000000001',marketplace:'US',fetchedAt:source.fetchedAt,target:{asin:'B000000001',title:'Brand 30 oz Tumbler',price:{amount:20,currency:'USD'},rating:4.5,reviewCount:50,reviewScope:'跨变体聚合需确认',source,attributes:{},categoryPath:[],recentPurchases:{raw:'500+ bought in past month'}},competitors:[],keywordEvidence:[],warnings:[],candidateCount:1}}
test('新网页初始不显示旧演示商品，明确要求数据助手',async()=>{const r=appRuntime();await new Promise(resolve=>setTimeout(resolve,15));const text=r.document.querySelector('#app').textContent;assert.ok(!text.includes('Animal Face Masks'));assert.ok(text.includes('把每个 ASIN，做成可持续优化的增长记录'));assert.ok(text.includes('数据助手已连接'));assert.equal(r.document.querySelector('#asin').value,'')});
test('一键研究仅将 ASIN 发给插件；Key 只在 DeepSeek 请求头，不进入存储报告',async()=>{const r=appRuntime();await new Promise(resolve=>setTimeout(resolve,15));r.document.querySelector('#asin').value='B000000001';await vm.runInContext('runAnalysis()',r.context);const research=r.sent.find(x=>x.action==='research');assert.deepEqual(JSON.parse(JSON.stringify(research.payload)),{asin:'B000000001',marketplace:'US'});assert.ok(!JSON.stringify(r.sent).includes(r.secret));assert.equal(vm.runInContext('researchError',r.context),'');assert.equal(r.http.length,1);assert.equal(r.http[0].url,'https://api.deepseek.com/chat/completions');assert.equal(r.http[0].options.headers.Authorization,`Bearer ${r.secret}`);assert.ok(!r.http[0].options.body.includes(r.secret));assert.ok(!vm.runInContext("localStorage.getItem('amazon_ops_reports')",r.context).includes(r.secret));assert.ok(r.document.querySelector('#app').textContent.includes('真实商品资料'))});
test('SIF 表格关联分析时传给 DeepSeek，不发给采集插件',async()=>{const r=appRuntime();await new Promise(resolve=>setTimeout(resolve,15));assert.ok(r.document.querySelector('#sifImportBtn'));vm.runInContext("sifExports.set('B000000001',{provider:'sif_user_export',targetAsin:'B000000001',marketplace:'US',period:'2026-09',importedAt:'2026-10-07',rows:[{keyword:'travel tumbler',monthlyVolume:1200,monthlyVolumeRaw:'1200',sourceAsin:'B000000002'}]})",r.context);r.document.querySelector('#asin').value='B000000001';await vm.runInContext('runAnalysis()',r.context);assert.equal(vm.runInContext('researchError',r.context),'');assert.ok(r.http[0].options.body.includes('travel tumbler'));assert.ok(!JSON.stringify(r.sent).includes('travel tumbler'));assert.ok(r.document.querySelector('#app').textContent.includes('SIF 表格已关联'))});


test('Listing 草稿页按作业表顺序先展示结构化作业表',async()=>{const r=appRuntime();await new Promise(resolve=>setTimeout(resolve,15));r.document.querySelector('#asin').value='B000000001';await vm.runInContext('runAnalysis()',r.context);vm.runInContext("state.tab='listing';render()",r.context);const text=r.document.querySelector('#app').textContent;assert.ok(text.includes('产品信息、需求拆解与市场验证'));assert.ok(text.includes('需求10'));assert.ok(text.includes('DeepSeek Listing 草稿'))});
