import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {Script} from 'node:vm';
const oldRequest="const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:personalKey,model:personalModel,data:{...state.data,data_source:state.source}})});const out=await r.json();if(!r.ok||out.mode!=='deepseek')throw new Error(out.error||out.message||'分析失败');";
let app=readFileSync('src/main.js','utf8');if(!app.includes(oldRequest))throw Error('前端调用结构已改变，请更新 Pages 生成器');
app=app.replace(oldRequest,"const out=await analyzeWithDeepSeek({apiKey:personalKey,model:personalModel,data:{...state.data,data_source:state.source}});");
app=app.replace('分析时资料会发给 DeepSeek，并使用你的 API 余额。','分析时浏览器直接连接 DeepSeek，使用你的 API 余额。');
const adapter=readFileSync('scripts/pages-api.mjs','utf8').replace('export async function','async function');
const code=adapter+'\n'+app;
new Script(code);
const css=readFileSync('src/style.css','utf8').replace(/@import[^;]+;/g,'');
const favicon=encodeURIComponent(readFileSync('favicon.svg','utf8'));
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="亚马逊 Listing、竞品和关键词运营工作台"><title>亚马逊运营助手</title><link rel="icon" href="data:image/svg+xml,${favicon}"><style>${css}</style></head><body><div id="app"></div><script>${code.replace(/<\/script/gi,'<\\/script')}</script></body></html>`;
if(html.includes('/api/analyze')||html.includes('chatgpt.site')||html.includes('fonts.googleapis.com'))throw Error('Pages 不能依赖旧服务或外部字体');
mkdirSync('docs',{recursive:true});writeFileSync('docs/index.html',html);
console.log('Pages build ok: standalone docs/index.html, direct DeepSeek, no old domain dependency');
