import test from 'node:test';import assert from 'node:assert/strict';import {deflateRawSync} from 'node:zlib';import {createRequire} from 'node:module';
import {parseDelimited,inspectSifRows,normalizeSifRows} from '../src/sif-import.mjs';import {readXlsxTables} from '../src/xlsx-reader.mjs';import {optimizationPrompt} from '../src/research/collector.mjs';
const require=createRequire(import.meta.url),{DOMParser}=require('linkedom');
const input={targetAsin:'B000000001',sourceAsin:'B000000002',period:'2026-09',marketplace:'US'};
test('SIF CSV 处理引号、逗号和换行，保留未知指标',()=>{const parsed=inspectSifRows(parseDelimited('\uFEFF关键词,月搜索量,流量占比,自然排名\r\n"tumbler, handle","1,200",25%,第1页第3位\r\n"travel\n cup",—,,\r\n'));const data=normalizeSifRows({...input,...parsed});assert.equal(data.rows[0].keyword,'tumbler, handle');assert.equal(data.rows[0].monthlyVolume,1200);assert.equal(data.rows[0].trafficShare,'25%');assert.equal(data.rows[1].monthlyVolume,null);assert.equal(data.rows[0].sourceAsin,input.sourceAsin);assert.throws(()=>parseDelimited('keyword\n"unfinished'),/未闭合/)});
test('SIF 表头不把搜索量排名映射为搜索量，允许用户手动映射',()=>{const parsed=inspectSifRows([['报告说明'],['关键词','搜索量排名','月搜索量','ASIN'],['tumbler','12','1.5K','B000000003']]);assert.equal(parsed.headerRow,1);assert.equal(parsed.mapping.monthlyVolume,2);assert.equal(normalizeSifRows({...input,...parsed}).rows[0].monthlyVolume,1500);const noVolume=inspectSifRows([['关键词','搜索量排名'],['tumbler','12']]);assert.equal(noVolume.mapping.monthlyVolume,-1);assert.equal(normalizeSifRows({...input,...noVolume}).rows[0].monthlyVolume,null)});
test('缺失周期或错误来源不得导入，同一来源重复词去重',()=>{const parsed=inspectSifRows([['关键词'],['Cup'],['cup']]);assert.throws(()=>normalizeSifRows({...input,...parsed,period:''}),/周期/);assert.throws(()=>normalizeSifRows({...input,...parsed,sourceAsin:'BAD'}),/ASIN/);assert.equal(normalizeSifRows({...input,...parsed}).rows.length,1)});
test('SIF 模型输入校验关联 ASIN，保留来源和周期并限制150行',()=>{const sifData={...input,rows:Array.from({length:160},(_,i)=>({keyword:'cup '+i,monthlyVolume:i,sourceAsin:input.sourceAsin}))};const bundle={asin:input.targetAsin,marketplace:'US',sifData};const p=optimizationPrompt(bundle),data=JSON.parse(p.user);assert.equal(data.sifData.rows.length,150);assert.equal(data.sifData.rows[0].monthlyVolume,159);assert.equal(data.sifData.period,'2026-09');assert.match(p.system,/排名改称搜索量/);assert.throws(()=>optimizationPrompt({...bundle,asin:'B000000004'}),/不匹配/)});
function zip(files){const local=[],central=[];let offset=0;for(const [name,xml] of Object.entries(files)){const filename=Buffer.from(name),plain=Buffer.from(xml),packed=deflateRawSync(plain),head=Buffer.alloc(30),dir=Buffer.alloc(46);head.writeUInt32LE(0x04034b50);head.writeUInt16LE(8,8);head.writeUInt32LE(packed.length,18);head.writeUInt32LE(plain.length,22);head.writeUInt16LE(filename.length,26);dir.writeUInt32LE(0x02014b50);dir.writeUInt16LE(8,10);dir.writeUInt32LE(packed.length,20);dir.writeUInt32LE(plain.length,24);dir.writeUInt16LE(filename.length,28);dir.writeUInt32LE(offset,42);local.push(head,filename,packed);central.push(dir,filename);offset+=head.length+filename.length+packed.length}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,directory,end])}
test('标准 XLSX 本地读取共享字符串和百分比，忽略公式执行及外部链接',async()=>{const files={'xl/workbook.xml':'<workbook xmlns:r="x"><sheets><sheet name="SIF关键词" r:id="rId1"/><sheet name="外部" r:id="rId2"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Target="https://evil.example/" TargetMode="External"/></Relationships>','xl/sharedStrings.xml':'<sst><si><t>关键词</t></si><si><t>月搜索量</t></si><si><t>流量占比</t></si><si><t>tumbler cup</t></si></sst>','xl/styles.xml':'<styleSheet><cellXfs><xf numFmtId="0"/><xf numFmtId="10"/></cellXfs></styleSheet>','xl/worksheets/sheet1.xml':'<worksheet><sheetData><row><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="s"><v>2</v></c></row><row><c r="A2" t="s"><v>3</v></c><c r="B2"><f>1000+500</f><v>1500</v></c><c r="C2" s="1"><v>0.25</v></c></row></sheetData></worksheet>'};const tables=await readXlsxTables(zip(files),{parseXml:text=>new DOMParser().parseFromString(text,'text/xml')});assert.equal(tables.length,1);assert.equal(tables[0].name,'SIF关键词');assert.deepEqual(tables[0].rows[1],['tumbler cup','1500','25%']);const data=normalizeSifRows({...input,...inspectSifRows(tables[0].rows)});assert.equal(data.rows[0].monthlyVolume,1500);assert.equal(data.rows[0].trafficShare,'25%');await assert.rejects(()=>readXlsxTables(Buffer.from('not excel')),/不完整/)});
