let sifExports=new Map();try{const saved=JSON.parse(localStorage.getItem('amazon_ops_sif')||'[]');if(Array.isArray(saved))sifExports=new Map(saved.slice(-10))}catch{}
const currentSif=()=>{const asin=currentAsinInput||state.data.asin;return state.researchBundle?.asin===asin?state.researchBundle.sifData||sifExports.get(asin):sifExports.get(asin)};
const beforeSifAccept=acceptResearch;
acceptResearch=function(bundle){beforeSifAccept(bundle);const saved=bundle.sifData||sifExports.get(bundle.asin);if(saved){bundle.sifData=saved;sifExports.set(bundle.asin,saved)}};
const beforeSifKeywords=researchKeywords;
researchKeywords=function(){const data=currentSif();return `${data?renderSifEvidence(data):'<section class="card"><h2>复用已有 SIF 数据</h2><p>导入 SIF 导出的关键词表，可结合搜索量、流量占比和排名优化文案。不需要重复购买数据服务。</p><button class="ghost" id="sifKeywordsImport">导入 SIF 关键词表</button></section>'}${beforeSifKeywords()}`};
function renderSifEvidence(data){return `<section class="card"><div class="card-title"><b>SIF 关键词依据</b><span class="tag">用户导出快照 · ${data.rows.length} 个词</span></div><p class="muted">美国站 · ${esc(data.period)} · 导入于 ${esc(prettyTime(data.importedAt))}。来源 ASIN 与每一行对应；流量词仍需核对与本品的相关性。</p><div class="table-scroll"><table><thead><tr><th>词 / 来源 ASIN</th><th>月搜索量</th><th>流量占比</th><th>自然 / 广告排名</th><th>CPC / 转化标签</th></tr></thead><tbody>${data.rows.slice(0,100).map(k=>`<tr><td>${esc(k.keyword)}<small>${esc(k.sourceAsin)}</small></td><td>${esc(k.monthlyVolumeRaw||'未提供')}</td><td>${esc(k.trafficShare||'未提供')}</td><td>${esc(k.naturalRank||'未提供')} / ${esc(k.adRank||'未提供')}</td><td>${esc(k.cpc||'未提供')}<small>${esc(k.conversionLabel||'未提供')}</small></td></tr>`).join('')}</tbody></table></div><p class="muted">界面显示前 100 行，完整已导入数据保存在本机。点击分析时将选取最多 150 行发给 DeepSeek；没有读取 SIF 登录凭证或绕过会员限制。</p></section>`}
const beforeSifRender=render;
render=function(){beforeSifRender();const actions=document.querySelector('.header-actions');if(actions&&!document.querySelector('#sifImportBtn')){actions.insertAdjacentHTML('afterbegin',`<button class="ghost" id="sifImportBtn">${currentSif()?'更新 SIF 关键词表':'导入 SIF 关键词表'}</button>`);document.querySelector('#sifImportBtn').disabled=researchBusy;document.querySelector('#sifImportBtn').onclick=showSifImport}document.querySelector('#sifKeywordsImport')?.addEventListener('click',showSifImport);if(state.section==='workspace'&&currentSif()){const notice=document.querySelector('.assistant-status');notice?.insertAdjacentHTML('beforeend',`<p>SIF 表格已关联：${currentSif().rows.length} 个关键词 · ${esc(currentSif().period)}，本次分析会结合这些数据。</p>`)}};
function showSifImport(){
 if(document.querySelector('#sifModal'))return;
 const target=(document.querySelector('#asin')?.value||currentAsinInput||state.data.asin||'').trim().toUpperCase();
 document.querySelector('.shell').inert=true;document.body.style.overflow='hidden';
 document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="sifModal" role="dialog" aria-modal="true" aria-labelledby="sifTitle"><div class="modal sif-modal"><div class="modal-kicker">使用小羊已有的 SIF 会员数据</div><h2 id="sifTitle">导入 SIF 关键词表</h2><p class="modal-sub">支持 XLSX、CSV、TSV。文件在本浏览器读取，确认后仅保存识别出的关键词字段；点击分析才发送给 DeepSeek。这里没有自动直连 SIF。</p><div class="sif-fields"><label>要优化的 ASIN<input id="sifTarget" maxlength="10" value="${esc(target)}" placeholder="目标商品 ASIN"></label><label>表格的数据来源 ASIN<input id="sifSource" maxlength="10" value="${esc(target)}" placeholder="本品或某个竞品 ASIN"></label><label>数据周期<input id="sifPeriod" placeholder="如 2026-09，或导出时的近30天"></label></div><label class="sif-file">选择 SIF 导出文件<input id="sifFile" type="file" accept=".xlsx,.csv,.tsv"></label><div id="sifSheets"></div><div id="sifMapping"></div><div id="sifPreview"></div><p id="sifError" class="text-error" role="status"></p><div class="modal-actions"><button class="ghost" id="cancelSif">取消</button><button class="primary" id="confirmSif" disabled>确认导入</button></div></div></div>`);
 const modal=document.querySelector('#sifModal');let tables=[],inspected=null;
 const close=()=>{modal.remove();document.querySelector('.shell').inert=false;document.body.style.overflow=''};document.querySelector('#cancelSif').onclick=close;modal.onkeydown=e=>{if(e.key==='Escape')close()};
 const labels={keyword:'关键词（必选）',monthlyVolume:'月搜索量',trafficShare:'流量占比',naturalRank:'自然排名',adRank:'广告排名',cpc:'CPC / 建议竞价',conversionLabel:'转化标签',keywordType:'关键词类型',asin:'每行来源 ASIN'};
 const preview=()=>{document.querySelector('#sifPreview').innerHTML=`<p class="muted">识别到表头在第 ${inspected.headerRow+1} 行，以下预览前 5 行。未识别的列可以手动选择；请勿把搜索量排名映射为月搜索量。</p><div class="table-scroll"><table><thead><tr>${inspected.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${inspected.rows.slice(0,5).map(row=>`<tr>${inspected.headers.map((_,i)=>`<td>${esc(String(row[i]??'').slice(0,150))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`};
 const selectSheet=index=>{inspected=inspectSifRows(tables[index].rows);document.querySelector('#sifMapping').innerHTML='<h3>核对表格列</h3><div class="sif-fields">'+Object.entries(labels).map(([field,label])=>`<label>${label}<select data-sif-field="${field}"><option value="-1">未提供</option>${inspected.headers.map((h,i)=>`<option value="${i}" ${inspected.mapping[field]===i?'selected':''}>${esc(h||'第'+(i+1)+'列')}</option>`).join('')}</select></label>`).join('')+'</div>';document.querySelectorAll('[data-sif-field]').forEach(s=>s.onchange=()=>{inspected.mapping[s.dataset.sifField]=Number(s.value)});preview();document.querySelector('#confirmSif').disabled=false};
 document.querySelector('#sifFile').onchange=async e=>{document.querySelector('#sifError').textContent='';document.querySelector('#confirmSif').disabled=true;try{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024)throw Error('表格超过 8MB，请在 SIF 缩小导出范围');const bytes=await f.arrayBuffer();if(/\.xlsx$/i.test(f.name)){tables=await readXlsxTables(bytes)}else if(/\.(csv|tsv)$/i.test(f.name)){let text=new TextDecoder('utf-8').decode(bytes);if(text.includes('\uFFFD'))text=new TextDecoder('gb18030').decode(bytes);tables=[{name:'关键词表',rows:parseDelimited(text)}]}else throw Error('请选择 SIF 导出的 Excel、CSV 或 TSV');document.querySelector('#sifSheets').innerHTML=`<label>工作表<select id="sifSheet">${tables.map((t,i)=>`<option value="${i}">${esc(t.name)}</option>`).join('')}</select></label>`;document.querySelector('#sifSheet').onchange=e=>selectSheet(Number(e.target.value));selectSheet(0)}catch(error){document.querySelector('#sifError').textContent=error.message}};
 document.querySelector('#confirmSif').onclick=()=>{try{const data=normalizeSifRows({rows:inspected.rows,mapping:inspected.mapping,targetAsin:document.querySelector('#sifTarget').value.trim().toUpperCase(),sourceAsin:document.querySelector('#sifSource').value.trim().toUpperCase(),period:document.querySelector('#sifPeriod').value,marketplace:'US'});sifExports.set(data.targetAsin,data);let persistenceError='';try{localStorage.setItem('amazon_ops_sif',JSON.stringify([...sifExports].slice(-10)))}catch{persistenceError='浏览器存储不足，SIF 数据仅保留在本次页面'}if(state.researchBundle?.asin===data.targetAsin){state.researchBundle.sifData=data;state.ai=null;saveResearch()}currentAsinInput=data.targetAsin;close();researchError=persistenceError;render()}catch(error){document.querySelector('#sifError').textContent=error.message}};
 document.querySelector('#sifTarget').focus();
}
render();
